server:
  port: 9090
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:userapi
    username: user
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
